#print('Crie uma tupla preenchida com os 20 primeiros colocados da Tabela do Campeonato Brasileiro de Futebol, na ordem de colocação. Depois mostre:\na) Os 5 primeiros times.\nb) Os últimos 4 colocados.\nc) Times em ordem alfabética.\nd) Em que posição está o time da Chapecoense.')

times = ('Ceará', 'Palmeiras', 'Atlético-GO', 'Flamengo', 'Avaí', 'Fortaleza', 'Bragantino', 'América-MG', 'Corinthians', 'Goiás', 'Cuiabá', 'Atlético-MG', 'Fluminense', 'Botafogo', 'Coritiba', 'Internacional', 'São Paulo', 'Athletico', 'Santos', 'Juventude')
print('-=' * 25)
print(f'Os times do brasileirão 2022 são: {times}')
print('-=' * 25)
print(f'Os primeiros cinco colocados da tabela são: {times[0:5]}')
print('-=' * 25)
print(f'Os quatro últimos colocados da tabela são: {times[16:]}')
print('-=' * 25)
print(f'Os times em ordem alfabética: {sorted(times)}')
print('-=' * 25)
print(f'O Flamengo está na {times.index("Flamengo")+1}ª posição!')
print('-=' * 25)
