print('Faça um programa que leia algo pelo teclado e mostre na tela\no seu tipo primitivo e todas as informações possíveis sobre ela:')

a = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(a))
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('Só tem espaços?', a.isspace())
print('É alfanumérico?', a.isalnum())
print('Está em maiúscula?', a.isupper())
print('Está em minúscula?', a.islower())
print('Está capitalizada?', a.istitle())
